name: Redeploy dailys api

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update config
        run: 'echo "$CONFIG_FILE" > config.json'
        env:
          CONFIG_FILE: ${{ secrets.DEPLOYED_CONFIG }}
      - name: Redeploying on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: GITHUB_REF
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            echo ${GITHUB_REF##*/}
            
